User.create!(username: "chotu", password: "chotu123")
User.create!(username: "singh",   password: "singh123")
User.create!(username: "tyagi",   password: "tyagi007")
User.create!(username: "montu",   password: "montu007")
User.create!(username: "soti",   password: "soti123")
User.create!(username: "shruti",   password: "shruti123")
User.create!(username: "divya",   password: "divya123")
